### ISSUE TITLE
Ore Dictionary breaks when an item has 2 oreDict entries.

### ISSUE THREAD

**Issue by Fxzy** [austinv11/PeripheralsPlusPlus#5] opened 2014-12-06 00:33 UTC
Title says it all. The title is multifunctional.

**Comment by rolandoislas** [comment] 2015-05-09 01:02
Tested with colored glass pane (Minecraft) and ender dust (AE2). Peripheral seems to be working as intended.

**Comment by austinv11** [comment] 2015-05-09 01:30
I'm gonna close this for now.

**Closed by austinv11** 2015-05-09 01:30 UTC
Labels: bug

**Comment by grandmind** [comment] 2015-05-09 04:32
I only ever tested it with woods. Not sure if it's still an issue.
