### ISSUE TITLE
Player Interface not working

### ISSUE THREAD

**Issue by Nathan1852** [austinv11/PeripheralsPlusPlus#150] opened 2016-02-28 20:01 UTC
The Player Interface doesn't seem to work. retrieveFromSlot does just nothing (and returns nothing)
and getStackInSlot doesn't return anything for the first 1000 Slots, even if I have multiples Items in my inventory

**Comment by grandmind** [comment] 2016-03-06 01:46
I was unable to reproduce this in any way. What do you mean the first 1000 slots? The player inventory only has 40.

**Comment by Nathan1852** [comment] 2016-03-06 12:58
I did a for loop from 1 to 1000, calling getStackInSlot for each number, thinking that I probably used the wrong slot numbers at first. But getStackInSlot never returned anything, even with more than enough Items in my Inventory

**Comment by grandmind** [comment] 2016-03-06 21:45
Ok, well, like I said, I was completely unable to reproduce this. It seems to work fine. Unless you can provide any more information, I'm going to close this for now.

**Closed by grandmind** 2016-03-06 21:45 UTC
