### ISSUE TITLE
Crash when Turtle moves next to RF Charger

### ISSUE THREAD

**Issue by Selim042** [austinv11/PeripheralsPlusPlus#37] opened 2015-03-03 03:14 UTC
Simple, Turtle moves next to RF Charger, causes crash.
ComputerCraft 1.73
Peripherals++ 1.2.2
http://pastebin.com/PKtKChqu

**Comment by grandmind** [comment] 2015-03-03 04:08
I was unable to reproduce this crash with the same versions of both CC and P++. Just to make sure I understand what you mean, you're saying that in a setup like this:
http://puu.sh/gkdwu/cded37de95.png
...the game will crash when telling the turtle to move forward with "go forward"?

**Comment by Selim042** [comment] 2015-03-03 23:12
Yea, when it the moves forward

**Comment by dakotaaesoph** [comment] 2015-03-08 11:53
This isn't fixed in 77 on multiplayer.

java.lang.UnsupportedOperationException
	at dan200.computercraft.shared.turtle.core.TurtleBrain.addFuel(TurtleBrain.java:510)
	at com.austinv11.peripheralsplusplus.tiles.TileEntityRFCharger.addFuel(TileEntityRFCharger.java:75)
	at com.austinv11.peripheralsplusplus.tiles.TileEntityRFCharger.func_145845_h(TileEntityRFCharger.java:69)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Fxzy** [comment] 2015-03-08 13:03
I've found that this happens, but not always. It seems like a random chance.

**Comment by dakotaaesoph** [comment] 2015-03-08 13:22
I set up my turtle for a Quarry and put the RF charger with a Tesseract next to where he dumps all of the goods in the chest. Any time he touches the RF charger, it crashes me.

**Comment by grandmind** [comment] 2015-03-08 15:19
You mentioned that this was on multiplayer. Does the crash affect only you or the whole server?

**Comment by dakotaaesoph** [comment] 2015-03-08 15:25
I don't know, I'm usually the only one on. It only crashes the client, though.

**Comment by austinv11** [comment] 2015-03-08 22:40
What version of ComputerCraft is this on?

**Comment by Fxzy** [comment] 2015-03-08 22:50
@austinv11 latest non-dev release

**Comment by dakotaaesoph** [comment] 2015-03-09 01:46
1.73

**Closed** 2015-03-10 22:40 UTC
Labels: investigation required
